### ISSUE TITLE
After upgrading vsCode to version 1.88.0 it stopped working

### ISSUE THREAD

**Issue by Sentinel-7** [GulomovCreative/vscode-modx#5]
This extension has been disabled because it does not support virtual workspaces.

![изображение](https://github.com/GulomovCreative/vscode-modx/assets/12987430/f962daa1-e1e5-409f-ac87-bcc120696159)

**Comment by GulomovCreative** [comment]
Проблема же решена [тут](1b2f23a9741a264f2ec5d821e341f4f8dc1e1b5c), да и с обновлением VSCode она не связана. Просто расширение до этого просто не работало с виртуальными пространствами, теперь работает.
